---
- name: Setup Passwordless Authentication on all nodes
  hosts: all
  gather_facts: false

  tasks:
    - name: Wait for SSH to be ready
      wait_for_connection:
        timeout: 60

    - name: Push control node public key to all instances
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
